[auth]
redirect_uri = 
cookie_secret = 

[auth.google]
client_id = 
client_secret = 
server_metadata_url = 

[auth.auth0]
domain = 
client_id = 
client_secret = 
server_metadata_url = 
client_kwargs = { "prompt" = "login"}